#ifndef __action_msgs__srv__CancelGoal__idl
#define __action_msgs__srv__CancelGoal__idl

#include "action_msgs/msg/GoalInfo.idl"
#include "builtin_interfaces/msg/Time.idl"
#include "unique_identifier_msgs/msg/UUID.idl"

module action_msgs
{
  module srv
  {
    const int8 ERROR_NONE = 0;
    const int8 ERROR_REJECTED = 1;
    const int8 ERROR_UNKNOWN = 2;

    struct CancelGoal_Request
    {
      builtin_interfaces::msg::Time stamp;
      unique_identifier_msgs::msg::UUID goal_id;
    };

    struct CancelGoal_Response
    {
      int8 return_code;
      sequence<action_msgs::msg::GoalInfo> goals_canceling;
    };
  };
};

#endif  // __action_msgs__srv__CancelGoal__idl
