#ifndef __action_msgs__msg__GoalStatus__idl
#define __action_msgs__msg__GoalStatus__idl

#include "unique_identifier_msgs/msg/UUID.idl"

module action_msgs
{
  module msg
  {
    const int8 STATUS_UNKNOWN = 0;
    const int8 STATUS_ACCEPTED = 1;
    const int8 STATUS_EXECUTING = 2;
    const int8 STATUS_CANCELING = 3;
    const int8 STATUS_SUCCEEDED = 4;
    const int8 STATUS_CANCELED = 5;
    const int8 STATUS_ABORTED = 6;

    struct GoalStatus
    {
      unique_identifier_msgs::msg::UUID goal_id;
      int8 status;
    };
  };
};

#endif  // __action_msgs__msg__GoalStatus__idl
